/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula10;

import Modelos.ContaBanco;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author mari
 */
public class TelaOperacoes extends javax.swing.JFrame {

    ContaBanco objConta = TelaMenu.objContaBanco;
    DefaultComboBoxModel model;

    public TelaOperacoes() {
        initComponents();
        ContaBanco objConta = TelaMenu.objContaBanco;

        atualizarDados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitular = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblCheque = new javax.swing.JLabel();
        rbtnSaque = new javax.swing.JRadioButton();
        rbtnDeposito = new javax.swing.JRadioButton();
        rbtnTransferencia = new javax.swing.JRadioButton();
        cbContaDestino = new javax.swing.JComboBox<>();
        btnROperacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        rbtnPix = new javax.swing.JRadioButton();
        cmbPix = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Conta"));
        jPanel1.setToolTipText("");

        lblTitular.setText("Titular:");

        lblSaldo.setText("Saldo:");

        lblCheque.setText("Cheque Especial:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitular)
                    .addComponent(lblSaldo)
                    .addComponent(lblCheque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCheque)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(rbtnSaque);
        rbtnSaque.setText("Saque");

        buttonGroup1.add(rbtnDeposito);
        rbtnDeposito.setText("Depósito");

        buttonGroup1.add(rbtnTransferencia);
        rbtnTransferencia.setText("Transferência");
        rbtnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTransferenciaActionPerformed(evt);
            }
        });

        btnROperacao.setText("Realizar Operação");
        btnROperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnROperacaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor :");

        buttonGroup1.add(rbtnPix);
        rbtnPix.setText("Tran.Pix");
        rbtnPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnROperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE)))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnSaque)
                            .addComponent(rbtnDeposito)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnTransferencia)
                                    .addComponent(rbtnPix))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbContaDestino, 0, 228, Short.MAX_VALUE)
                                    .addComponent(cmbPix, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addComponent(rbtnSaque)
                .addGap(9, 9, 9)
                .addComponent(rbtnDeposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTransferencia)
                    .addComponent(cbContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPix)
                    .addComponent(cmbPix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnROperacao)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnROperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnROperacaoActionPerformed
        try {
            double valor = Double.parseDouble(txtValor.getText());

            if (rbtnDeposito.isSelected()) {
                objConta.deposito(valor);
            } else if (rbtnSaque.isSelected()) {
                objConta.saque(valor);
            } else if (rbtnTransferencia.isSelected()) {

                ContaBanco objContaRecuperacao = (ContaBanco) cbContaDestino.getSelectedItem();

                if (cbContaDestino.getSelectedIndex() >= 0) {
                    objConta.transferir(objContaRecuperacao, valor);
                }

            } else if (rbtnPix.isSelected()) {

                ContaBanco objContaRecuperacao = (ContaBanco) cbContaDestino.getSelectedItem();

                if (cbContaDestino.getSelectedIndex() >= 0) {
                    objConta.transferenciaPIX(valor, objContaRecuperacao);
                }

            }
            atualizarDados();

        } catch (NumberFormatException ex) {
            System.out.println("Erro: " + ex.getMessage());

        } catch (Exception ex) {
            System.out.println("Erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_btnROperacaoActionPerformed

    private void rbtnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTransferenciaActionPerformed
        model = new DefaultComboBoxModel();
        for (ContaBanco item : TelaMenu.arrContas) {
            if (!item.getConta().equals(objConta.getConta())) {
                model.addElement(item);
                cbContaDestino.setModel(model);
            }
        }
    }//GEN-LAST:event_rbtnTransferenciaActionPerformed

    private void rbtnPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPixActionPerformed
        model = new DefaultComboBoxModel();
        for (ContaBanco item : TelaMenu.arrContas) {
            if (!item.getConta().equals(objConta.getConta())) {
                model.addElement(item.getChavePIX());
                cmbPix.setModel(model);
            }
        }
    }//GEN-LAST:event_rbtnPixActionPerformed

    private void atualizarDados() {

        buttonGroup1.clearSelection();
        lblTitular.setText("Titular: " + TelaMenu.objContaBanco.getTitular());
        lblSaldo.setText("Saldo: R$" + TelaMenu.objContaBanco.getSaldo());
        lblCheque.setText("Cheq.Especial: R$" + TelaMenu.objContaBanco.getChequeEspecial());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOperacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnROperacao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbContaDestino;
    private javax.swing.JComboBox<String> cmbPix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCheque;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JRadioButton rbtnDeposito;
    private javax.swing.JRadioButton rbtnPix;
    private javax.swing.JRadioButton rbtnSaque;
    private javax.swing.JRadioButton rbtnTransferencia;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
